# fly -t concourse set-pipeline --config './concourse.yaml' --pipeline 'docker-draw.io' --load-vars-from ./concourse.vars

resources:
  - name: version
    type: semver
    source:
      driver: git
      uri: https://github.com/jgraph/draw.io.git
      branch: master
      file: VERSION
  
  - name: docker-draw.io
    type: git
    source:
      uri: https://github.com/fjudith/docker-draw.io.git
      branch: master
  
  - name: "draw.io-latest"
    type: registry-image
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/draw.io
      tag: latest
  - name: "draw.io-alpine"
    type: registry-image
    source:
      username: ((registry-username))
      password: ((registry-password))
      repository: ((registry-repo))/draw.io
      tag: alpine

jobs:
  - name: build-and-push-debian
    public: true
    plan:
    - get: version
      trigger: true
    - get: docker-draw.io
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: dullest/oci-build-task
            # repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-draw.io/debian/
          DOCKERFILE: ./docker-draw.io/debian/Dockerfile
        inputs:
          - name: docker-draw.io
          - name: version
        outputs:
          - name: image
        run:
          path: build
    - put: draw.io-latest
      params: {image: image/image.tar, additional_tags: version/version}

  - name: build-and-push-alpine
    public: true
    plan:
    - get: version
      trigger: true
    - get: docker-draw.io
    - task: write-additional-tags
      config:
        platform: linux
        image_resource:
          type: registry-image
          source: { repository: busybox }
        inputs:
            - name: version
        run:
          path: sh
          args:
            - -exc
            - echo "$(cat version/version)-alpine" > additionnal_tags/version
        outputs:
          - name: additionnal_tags
    - task: build
      privileged: true
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: dullest/oci-build-task
            # repository: vito/oci-build-task
        params:
          CONTEXT: ./docker-draw.io/alpine/
          DOCKERFILE: ./docker-draw.io/alpine/Dockerfile
        inputs:
          - name: additionnal_tags
          - name: docker-draw.io
        outputs:
          - name: image
        run:
          path: build
    - put: draw.io-alpine
      params: {image: image/image.tar, additional_tags: additionnal_tags/version}
